# docker-compose.yml
version: '3.8'

services:
  # 네트워크 내에서 'db'로 호출 가능
  # 1. DB 서비스
  db:
    image: postgres:15
    container_name: gaemi_db
    restart: always

    environment:
      POSTGRES_USER: gaemi
      POSTGRES_PASSWORD: gaemigaemi11 
      POSTGRES_DB: gaemi_ai

    ports:
      - "5432:5432"

    volumes:
      # (영속성) 컨테이너 삭제되어도 데이터를 볼륨에 안전하게 보관
      - postgres_data:/var/lib/postgresql/data
      # (초기화) 컨테이너가 처음 생성될 때, 자동으로 .sql 파일 실행
      - ./config/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # 현재 폴더의 'data' 디렉토리 -> 컨테이너 내부 '/docker-data' 디렉토리로 연결
      - ./config/postgres/data:/docker-data

  # 2. 백엔드 서비스
  backend:
    build:
      context: ./backend-pjt
    container_name: gaemi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend-pjt:/app
    environment:
      - POSTGRES_DB=gaemi_ai
      - POSTGRES_USER=gaemi
      - POSTGRES_PASSWORD=gaemigaemi11
      - POSTGRES_HOST=db
    depends_on:
      - db
  
  # 3. 프론트엔드 서비스
  frontend:
    build:
      context: ./frontend-pjt
    container_name: gaemi_front
    ports:
      - "5173:5173"   # Vite 기본 포트
    volumes:
      - ./frontend-pjt:/app
      - /app/node_modules # 호스트의 node_modules 동기화 방지
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"] 
    depends_on:
      - backend
  
  # 4. zookeeper (Kafka 관리자)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: gaemi_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  # 5. kafka 
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: gaemi_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     # [네트워크 설정]
      # - 내부 통신 (Producer->Kafka): kafka:29092
      # - 외부 접속 (Host->Kafka): localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # 싱글 노드 필수 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data

  # Kafka UI 서비스
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: gaemi_kafka_ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Gaemi-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=gaemi_kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=gaemi_zookeeper:2181
    depends_on:
      - kafka

  # 6. 주식 데이터 수집기 (Producer)
  producer-stock:
    build:
      context: ./data-pjt/producer-stock
    container_name: gaemi_producer_stock
    volumes:
      - ./data-pjt/producer-stock:/app
    env_file:
      - ./data-pjt/producer-stock/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka
    restart: on-failure

  # 7. 뉴스 데이터 수집기 (Procuer2)
  producer-news:
    build:
      context: ./data-pjt/producer-news
    container_name: gaemi_producer_news
    volumes:
      - ./data-pjt/producer-news:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka
    restart: on-failure

   # 8. Flink JobManager
  flink-jobmanager:
    build:
      context: ./data-pjt/flink
      dockerfile: Dockerfile-flink
    image: gaemi-flink-jobmanager:1.18
    platform: linux/amd64  # 추가
    container_name: gaemi_flink_jobmanager
    ports:
      - "8081:8081"   # Flink Web UI
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    depends_on:
      - kafka
    volumes:
      - ./data-pjt/flink-jobs:/opt/flink/usrlib/jobs
      - ./data-pjt/flink/flink-connector-kafka-3.2.0-1.18.jar:/opt/flink/lib/flink-connector-kafka-3.2.0-1.18.jar
      - ./data-pjt/flink/kafka-clients-3.5.1.jar:/opt/flink/lib/kafka-clients-3.5.1.jar
   
  # 9. Flink TaskManager
  flink-taskmanager:
    build:
      context: ./data-pjt/flink # JobMagaer랑 통일 / Job, Task Manager는 역할만 다르고 똑같은 소프트웨어 -> 둘 다 같은 파이썬 버전, 라이브러리, kafka 커넥트를 가지고 있어야함
      dockerfile: Dockerfile-flink
    platform: linux/amd64  # 추가
    image: gaemi-flink-taskmanager:1.18
    container_name: gaemi_flink_taskmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    depends_on:
      - flink-jobmanager
    volumes:
      - ./data-pjt/flink-jobs:/opt/flink/usrlib/jobs # TaskManager도 코드를 알아야함 -> 볼륨 마운트 필수
      - ./data-pjt/flink/flink-connector-kafka-3.2.0-1.18.jar:/opt/flink/lib/flink-connector-kafka-3.2.0-1.18.jar
      - ./data-pjt/flink/kafka-clients-3.5.1.jar:/opt/flink/lib/kafka-clients-3.5.1.jar

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: gaemi_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: gaemi_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

# Docker가 관리할 볼륨 정의
volumes:
  postgres_data:
  zookeeper_data:
  kafka_data:
  esdata: