# Generated by Django 5.2.8 on 2025-11-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='Watchlist_id',
            new_name='watchlist_id',
        ),
    ]
