# Generated by Django 5.2.8 on 2025-11-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggeredNotification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'triggered_notifications',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=20)),
                ('operator', models.CharField(max_length=10)),
                ('target_value', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockmaster')),
            ],
            options={
                'db_table': 'user_notification_rules',
            },
        ),
    ]
