FROM flink:1.17.1-scala_2.12-java11

# Python 설치
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

# PyFlink 설치
RUN pip install apache-flink==1.17.1

# Kafka Connector (KafkaSource 포함)
ADD https://repo1.maven.org/maven2/org/apache/flink/flink-connector-kafka/1.17.1/flink-connector-kafka-1.17.1.jar \
    /opt/flink/lib/

# Kafka Client
ADD https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar \
    /opt/flink/lib/

# Python job 저장 폴더 생성
RUN mkdir -p /opt/flink/usrlib

WORKDIR /opt/flink
