FROM flink:1.18.1-scala_2.12-java11

USER root

# 1. 시스템 패키지 및 파이썬 설치
RUN apt-get update --fix-missing && \
    apt-get install -y --fix-missing python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

# 2. PyFlink 및 필요한 라이브러리 설치
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install "apache-flink==1.18.1" requests protobuf beautifulsoup4 openai tiktoken psycopg2-binary
    
WORKDIR /opt/flink

USER flink
