FROM flink:1.18.1-scala_2.12-java11

USER root

RUN apt-get update --fix-missing && \
    apt-get install -y --fix-missing python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install "apache-flink==1.18.1" requests protobuf

WORKDIR /opt/flink

USER flink
