# Generated by Django 5.2.8 on 2025-11-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('stock_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=100)),
                ('market_type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '종목 마스터',
                'verbose_name_plural': '종목 마스터 목록',
                'db_table': 'stock_master',
                'managed': False,
            },
        ),
    ]
