# Generated by Django 5.2.9 on 2025-12-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='해당 주차 시작일 (월요일)')),
                ('end_date', models.DateField(help_text='해당 주차 종료일 (금요일)')),
                ('weekly_return', models.FloatField(help_text='주간 수익률 (%)')),
                ('weekly_high', models.IntegerField(help_text='주간 최고가')),
                ('weekly_low', models.IntegerField(help_text='주간 최저가')),
                ('start_price', models.IntegerField(help_text='주초 시가')),
                ('end_price', models.IntegerField(help_text='주말 종가')),
                ('summary_text', models.TextField(help_text='AI가 요약한 주간 흐름')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(help_text='리포트 대상 종목', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='stocks.stockmaster')),
            ],
            options={
                'db_table': 'weekly_reports',
                'ordering': ['-start_date'],
                'unique_together': {('stock', 'start_date')},
            },
        ),
    ]
